name: kebontebu_casino
description: Demo cross-platform casino app (KEBONTEBU) with multiplayer prototype
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  provider: ^6.0.0
  socket_io_client: ^2.0.0
  http: ^0.13.6
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true